[package]
name = "intcode-asm"
version = "0.1.0"
authors = ["Benedikt Werner <1benediktwerner@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2"
pest_derive = "2"
clap = "2.33"
intcode-vm = { path = "../vm" }
